### ISSUE TITLE
Painting of navigation areas

### ISSUE THREAD

**Issue by avril-gh** [Zylann/godot_terrain_plugin#15]
Possible to add painting of navigation areas where player may use navigation like in navdemo ?

**Comment by Zylann** [comment]
This plugin isn't maintained anymore, you should suggest this here instead: https://github.com/Zylann/godot_heightmap_module

**Comment by avril-gh** [comment]
um...
I know theres a 3.0 version, but Godot 3.0 is in developement for 2 years allready, and it seems like there might be another years before it reach production ready stage and then possible another long time  before it implements GL 2.x compatibility. (if it even do this)

So its like _waiting for a Godot who never came_... while we use Godot 2.1.x currently.

Your plugin is really awesome, theres perhaps many people who would love to use it with navigation mode in his projects...

**Comment by Zylann** [comment]
The reason why I shifted to a 3.0 C++ module is that:
1) The plugin cannot become production ready because it hits GDScript limits
2) It takes a lot of work to maintain both a 3.0 module and 2.1 at the same time

So unless you are willing to make a 2.1 version of the module or contribute to the GDScript one, I won't be doing that because my free time is limited^^"

**Comment by avril-gh** [comment]
since project is no more maintained, closing issue to decrease issues count.
